openapi: 3.0.3
info:
  title: Lob Accounts Reverse Geocode Lookups API
  version: 1.22.0
  description: 'The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p>

    '
  license:
    name: MIT
    url: https://mit-license.org/
  contact:
    name: Lob Developer Experience
    url: https://support.lob.com/
    email: lob-openapi@lob.com
  termsOfService: https://www.lob.com/legal
servers:
- url: https://api.lob.com/v1
  description: production
security:
- basicAuth: []
tags:
- name: Reverse Geocode Lookups
  description: 'Find a list of zip codes associated with a valid US location via latitude and longitude. <br> <div class="back-to-top" ><a href="#" onclick="toTopLink()">back to top</a></div>

    '
paths:
  /us_reverse_geocode_lookups:
    post:
      operationId: reverse_geocode_lookup
      summary: Reverse Geocode Lookup
      description: Reverse geocode a valid US location with a live API key.
      tags:
      - Reverse Geocode Lookups
      parameters:
      - in: query
        name: size
        schema:
          type: integer
          minimum: 1
          default: 5
          maximum: 50
          example: 5
        description: Determines the number of locations returned. Possible values are between 1 and 50 and any number higher will be rounded down to 50. Default size is a list of 5 reverse geocoded locations.
        required: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/location'
            example:
              latitude: 37.7749
              longitude: 122.4194
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/location'
            example:
              latitude: 37.7749
              longitude: 122.4194
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/location'
            example:
              latitude: 37.7749
              longitude: 122.4194
      responses:
        '200':
          $ref: '#/components/responses/reverse_geocode_lookups'
        default:
          $ref: '#/components/responses/reverse_geocode_lookups_error'
      x-codeSamples:
      - lang: Shell
        source: "curl https://api.lob.com/v1/us_reverse_geocode_lookups \\\n  -u <YOUR_LIVE_API_KEY>: \\\n  -d \"latitude=37.7749\" \\\n  -d \"longitude=122.4194\" \\\n"
        label: CURL
      - lang: Typescript
        source: "const ReverseGeocodeLookup = new ReverseGeocodeLookupsApi(av_config);\nconst coordinates = new Location({\n  latitude: 37.777456,\n  longitude: -122.393039\n});\ntry {\n  const geocode = await ReverseGeocodeLookup.lookup(coordinates);\n} catch (err: any) {\n  console.error(err);\n}\n"
        label: TYPESCRIPT
      - lang: Javascript
        source: "Lob.reverseGeocodeLookups.lookup({\n  latitude: 37.7749,\n  longitude: 122.4194\n}, function (err, res) {\n  console.log(err, res);\n});\n"
        label: NODE
      - lang: Ruby
        source: "reverseGeocodeLookupsApi = ReverseGeocodeLookupsApi.new(config)\n\ncoordinates = Location.new({\n  latitude: 37.777456,\n  longitude: -122.393039,\n})\n\nbegin\n  geocode = reverseGeocodeLookupsApi.lookup(coordinates)\nrescue => err\n  p err.message\nend\n"
        label: RUBY
      - lang: Python
        source: "with ApiClient(configuration) as api_client:\n  api = ReverseGeocodeLookupsApi(api_client)\n\ncoordinates = Location(\n  latitude = 37.777456,\n  longitude = -122.393039,\n)\n\ntry:\n  geocode = api.lookup(coordinates)\nexcept ApiException as e:\n  print(e)\n"
        label: PYTHON
      - lang: PHP
        source: "$apiInstance = new OpenAPI\\Client\\Api\\ReverseGeocodeLookupsApi($config, new GuzzleHttp\\Client());\n\n$coordinates = new OpenAPI\\Client\\Model\\Location(array(\n    \"latitude\" =>  \"37.777456\",\n    \"longitude\" =>  \"-122.393039\",\n));\n\ntry {\n    $result = $apiInstance->lookup($coordinates);\n} catch (Exception $e) {\n    echo $e->getMessage(), PHP_EOL;\n}\n"
        label: PHP
      - lang: Java
        source: "ReverseGeocodeLookupsApi apiInstance = new ReverseGeocodeLookupsApi(config);\n\nLocation location = new Location();\nlocation.setlatitude(37.777456f);\nlocation.setlongitude(-122.393039f);\n\ntry {\n  apiInstance.lookup(location, null);\n} catch (ApiException e) {\n  e.printStackTrace();\n}\n"
        label: JAVA
      - lang: Elixir
        source: "Lob.ReverseGeocodeLookup.lookup(%{\n  latitude: 37.7749,\n  longitude: 122.4194\n})\n"
        label: ELIXIR
      - lang: CSharp
        source: "ReverseGeocodeLookupsApi api = new ReverseGeocodeLookupsApi(config);\n\nLocation location = new Location(\n  37.777456f,\n  -122.393039f\n);\n\ntry {\n  api.lookup(location, null);\n} catch (ApiException e) {\n  Console.WriteLine(e.ToString());\n}\n"
        label: CSHARP
      - lang: Go
        source: "var context = context.Background()\ncontext = context.WithValue(context, lob.ContextBasicAuth, lob.BasicAuth{UserName: os.Getenv(\"<YOUR_API_KEY>\")})\n\nvar apiClient = *lob.NewAPIClient(configuration)\n\nvar location = *lob.NewLocationWithDefaults()\nlocation.SetLatitude(37.777456)\nlocation.SetLongitude(122.393039)\n\nresp, _, err := apiClient.ReverseGeocodeLookupsApi.Lookup(context).Location(location).Execute()\n\nif err != nil {\n    return err\n}\n"
        label: GO
components:
  headers:
    ratelimit-reset:
      description: 'The time at which the rate limit window resets in  <a href="https://en.wikipedia.org/wiki/Unix_time" target="_blank">UTC epoch seconds</a>

        '
      schema:
        type: integer
        example: 1528749846
    ratelimit-remaining:
      description: The number of requests remaining in the current window.
      schema:
        type: integer
        example: 100
    ratelimit-limit:
      description: The rate limit for a given endpoint.
      schema:
        type: integer
        example: 150
  schemas:
    reverse_geocode:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/reverse_geocode_id'
        addresses:
          type: array
          description: 'list of addresses

            '
          items:
            $ref: '#/components/schemas/addresses'
        object:
          type: string
          description: Value is resource type.
          enum:
          - us_reverse_geocode_lookup
          default: us_reverse_geocode_lookup
    components:
      type: object
      description: A nested object containing a breakdown of each component of a reverse geocoded response.
      required:
      - zip_code
      - zip_code_plus_4
      properties:
        zip_code:
          type: string
          description: The 5-digit ZIP code
          pattern: ^\d{5}$
        zip_code_plus_4:
          allOf:
          - description: A 4-digit ZIP add-on code
          - $ref: '#/components/schemas/zip_code_plus_4'
    location:
      type: object
      required:
      - latitude
      - longitude
      properties:
        latitude:
          type: number
          minimum: -90
          maximum: 90
          format: float
          description: 'A positive or negative decimal indicating the geographic latitude of the address, specifying the north-to-south position of a location. This should be input with `longitude` to pinpoint locations on a map.

            '
          nullable: true
        longitude:
          type: number
          minimum: -180
          maximum: 180
          format: float
          description: 'A positive or negative decimal indicating the geographic longitude of the address, specifying the north-to-south position of a location. This should be input with `latitude` to pinpoint locations on a map.

            '
          nullable: true
    addresses:
      type: object
      properties:
        components:
          $ref: '#/components/schemas/components'
        location_analysis:
          $ref: '#/components/schemas/location_analysis'
    error:
      type: object
      description: Lob uses RESTful HTTP response codes to indicate success or failure of an API request. In general, 2xx indicates success, 4xx indicate an input error, and 5xx indicates an error on Lob's end.
      required:
      - error
      properties:
        error:
          type: object
          required:
          - message
          - status_code
          - code
          properties:
            message:
              type: string
              description: A human-readable message with more details about the error
              example: Rate limit exceeded. Please wait 5 seconds and try your request again.
            status_code:
              $ref: '#/components/schemas/failure_status_code'
            code:
              type: string
              enum:
              - bad_request
              - conflict
              - feature_limit_reached
              - internal_server_error
              - invalid
              - not_deletable
              - not_found
              - request_timeout
              - service_unavailable
              - unrecognized_endpoint
              - unsupported_lob_version
              - address_length_exceeds_limit
              - bank_account_already_verified
              - bank_error
              - billing_address_required
              - custom_envelope_inventory_depleted
              - deleted_bank_account
              - failed_deliverability_strictness
              - file_pages_below_min
              - file_pages_exceed_max
              - file_size_exceeds_limit
              - foreign_return_address
              - inconsistent_page_dimensions
              - invalid_bank_account
              - invalid_bank_account_verification
              - invalid_check_international
              - invalid_country_covid
              - invalid_file
              - invalid_file_dimensions
              - invalid_file_download_time
              - invalid_file_url
              - invalid_image_dpi
              - invalid_international_feature
              - invalid_perforation_return_envelope
              - invalid_template_html
              - mail_use_type_can_not_be_null
              - merge_variable_required
              - merge_variable_whitespace
              - payment_method_unverified
              - pdf_encrypted
              - special_characters_restricted
              - unembedded_fonts
              - email_required
              - invalid_api_key
              - publishable_key_not_allowed
              - rate_limit_exceeded
              - unauthorized
              - unauthorized_token
              description: 'A pre-defined string identifying an error. Error codes fall into three categories:


                **GENERIC**

                * `bad_request` - 422: an invalid request was made. See error message for details.

                * `conflict` - 409/422: this operation would leave data in a conflicted state.

                * `feature_limit_reached` - 403: the account has reached its resource limit and requires upgrading to add more.

                * `internal_server_error` - 500: an error has occured on Lob''s servers. Please try request again.

                * `invalid` - 422: an invalid request was made. See error message for details.

                * `not_deletable` - 422: an attempt was made to delete a resource, but the resource cannot be deleted.

                * `not_found` - 404: the requested resource was not found.

                * `request_timeout` - 408: the request took too long. Please try again.

                * `service_unavailable` - 503: the Lob servers are temporarily unavailable. Please try agian.

                * `unrecognized_endpoint` - 404: the requested endpoint doesn''t exist.

                * `unsupported_lob_version` - 422: an unsupported Lob API version was requested.


                **ADVANCED**

                * `address_length_exceeds_limit` - 422: the sum of to.address_line1 and to.address_line2 cannot surpass 50 characters.

                * `bank_account_already_verified` - 422: the bank account has already been verified.

                * `bank_error` - 422: there''s an issue with the bank account.

                * `billing_address_required` - 403: in order to create a live mail piece, your account needs to set up a billing address.

                * `custom_envelope_inventory_depleted` - 422: custom envelope inventory is depleted, and more will need to be ordered.

                * `deleted_bank_account` - 404: checks cannot be created with a deleted bank account.

                * `failed_deliverability_strictness` - 422: the `to` address doesn''t meet strictness requirements. See <a href="https://dashboard.lob.com/#/settings/account" target="_blank">Account Settings</a> to configure strictness.

                * `file_pages_below_min` - 422: not enough pages.

                * `file_pages_exceed_max` - 422: too many pages.

                * `file_size_exceeds_limit` - 422: the file size is too large. See description for details.

                * `foreign_return_address` - 422: the `from` address must be a US address.

                * `inconsistent_page_dimensions` - 422: all pages of the input file must have the same dimensions.

                * `invalid_bank_account` - 422: the provided bank routing number is invalid.

                * `invalid_bank_account_verification` - 422: verification amounts do not match.

                * `invalid_check_international` - 422: checks cannot be sent internationally.

                * `invalid_country_covid` - 422: the postal service in the specified country is currently unable to process the request due to COVID-19 restrictions.

                * `invalid_file` - 422: the file is invalid.

                * `invalid_file_dimensions` - 422: file dimensions are incorrect for the selected mail type.

                * `invalid_file_download_time` - 422: file download from remote server took too long.

                * `invalid_file_url` - 422: the file URL when creating a resource is invalid.

                * `invalid_image_dpi` - 422: DPI must be at least 300.

                * `invalid_international_feature` - 422: the specified product cannot be sent to the destination.

                * `invalid_perforation_return_envelope` - 422: both `return_envelope` and `perforation` must be used together.

                * `invalid_template_html` - 422: the provided HTML is invalid.

                * `mail_use_type_can_not_be_null` - 422: use_type must be one of "marketing" or "operational". Alternatively, an admin can set the account default use type in Account Settings.

                * `merge_variable_required` - 422: a required merge variable is missing.

                * `merge_variable_whitespace` - 422: merge variable names cannot contain whitespace.

                * `payment_method_unverified` - 401: you must have a verified bank account or credit card to submit live requests.

                * `pdf_encrypted` - 422: an encrypted PDF was provided.

                * `special_characters_restricted` - 422: cannot use special characters for merge variable names.

                * `unembedded_fonts` - 422: the provided PDF contains non-standard unembedded fonts. See description for details.


                **AUTHENTICATION**

                * `email_required` - 401: account must have a verified email address before creating live resources.

                * `invalid_api_key` - 401/403: the API key is invalid.

                * `publishable_key_not_allowed` - 403: the requested operation needs a secret key, not a publishable key. See [API Keys](#section/API-Keys) for more information.

                * `rate_limit_exceeded` - 429: requests were sent too quickly and must be slowed down.

                * `unauthorized` - 401: the request isn''t authorized.

                * `unauthorized_token` - 401: token isn''t authorized.

                '
    failure_status_code:
      type: integer
      enum:
      - 401
      - 403
      - 404
      - 413
      - 422
      - 429
      - 500
      description: "A conventional HTTP status code:\n  * `401` - Authorization error with your API key or account\n  * `403` - Forbidden error with your API key or account\n  * `404` - The requested item does not exist\n  * `413` - Payload too large\n  * `422` - The query or body parameters did not pass validation\n  * `429` - Too many requests have been sent with an API key in a given amount of time\n  * `500` - An internal server error occurred, please contact support@lob.com\n"
    reverse_geocode_id:
      type: string
      description: Unique identifier prefixed with `us_reverse_geocode_`.
      pattern: ^us_reverse_geocode_[a-zA-Z0-9_]+$
    location_analysis:
      type: object
      description: A nested object containing a breakdown of the analysis of a reverse geocoded location.
      required:
      - latitude
      - longitude
      - distance
      properties:
        latitude:
          type: number
          minimum: -90
          maximum: 90
          format: float
          description: 'A positive or negative decimal indicating the geographic latitude of the address, specifying the north-to-south position of a location. This should be used with `longitude` to pinpoint locations on a map. Will not be returned for undeliverable addresses or military addresses (state is `AA`, `AE`, or `AP`).

            '
          nullable: true
        longitude:
          type: number
          minimum: -180
          maximum: 180
          format: float
          description: 'A positive or negative decimal indicating the geographic longitude of the address, specifying the north-to-south position of a location. This should be used with `latitude` to pinpoint locations on a map. Will not be returned for undeliverable addresses or military addresses (state is `AA`, `AE`, or `AP`).

            '
          nullable: true
        distance:
          type: number
          format: float
          description: 'The distance from the input location to this exact zip code in miles.

            '
    zip_code_plus_4:
      type: string
      pattern: ^\d{4}$
  responses:
    reverse_geocode_lookups:
      description: Returns a zip lookup object if a valid zip was provided.
      headers:
        ratelimit-limit:
          $ref: '#/components/headers/ratelimit-limit'
        ratelimit-remaining:
          $ref: '#/components/headers/ratelimit-remaining'
        ratelimit-reset:
          $ref: '#/components/headers/ratelimit-reset'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/reverse_geocode'
          example:
            id: us_reverse_geocode_8a013f3e
            addresses:
            - components:
                zip_code: '94107'
                zip_code_plus_4: '1702'
              location_analysis:
                latitude: 37.78271
                longitude: -122.416202
                distance: 1.32
            - components:
                zip_code: '94107'
                zip_code_plus_4: '1702'
              location_analysis:
                latitude: 37.782917
                longitude: -122.416131
                distance: 1.33
    reverse_geocode_lookups_error:
      description: Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
          example:
            error:
              code: invalid
              message: latitude is required
              status_code: 422
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
x-webhooks:
  events:
    post:
      summary: Events
      description: Information about an event
      operationId: event
      tags:
      - Events
      responses:
        '200':
          $ref: '#/components/responses/events'
  tracking_events:
    post:
      summary: Tracking Events
      description: Information about tracking events
      operationId: tracking_event
      tags:
      - Tracking Events
      responses:
        '200':
          $ref: '#/components/responses/tracking_events'
x-tagGroups:
- name: Overview
  tags:
  - Introduction
  - Authentication
  - Getting Started
  - SDKs and Tools
- name: Address Book
  tags:
  - Addresses
  - National Change of Address
- name: Print and Mail API
  tags:
  - Postcards
  - Self Mailers
  - Letters
  - Checks
  - Snap Packs
  - Booklets
  - Bank Accounts
  - Templates
  - Resource Proofs
  - Template Versions
  - Template Design
  - Manage Mail
- name: Campaigns API (BETA)
  tags:
  - Campaigns
  - Creatives
  - Uploads
- name: Informed Delivery Campaign API
  tags:
  - Informed Delivery Campaign
- name: Address Verification API
  tags:
  - US Verifications
  - US Verification Types
  - US Autocompletions
  - Reverse Geocode Lookups
  - Zip Lookups
  - Identity Validation
  - Intl Verifications
- name: Webhooks
  tags:
  - Webhooks
  - Events
  - Tracking Events
- name: Special Features
  tags:
  - Billing Groups
  - Buckslips
  - Buckslip Orders
  - Cards
  - Card Orders
  - QR Codes
  - URL Shortener
- name: Appendix
  tags:
  - Beta Program
  - Errors
  - Rate Limiting
  - Requests and Responses
  - Test and Live Environments
  - Versioning and Changelog
