openapi: 3.0.3
info:
  title: Lob Accounts Buckslip Orders API
  version: 1.22.0
  description: 'The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p>

    '
  license:
    name: MIT
    url: https://mit-license.org/
  contact:
    name: Lob Developer Experience
    url: https://support.lob.com/
    email: lob-openapi@lob.com
  termsOfService: https://www.lob.com/legal
servers:
- url: https://api.lob.com/v1
  description: production
security:
- basicAuth: []
tags:
- name: Buckslip Orders
  description: 'The Buckslip Orders endpoint allows you to easily create buckslip orders for existing buckslips.

    The API provides endpoints for creating buckslip orders and listing buckslip orders for a given buckslip.

    <div class="back-to-top" ><a href="#" onclick="toTopLink()">back to top</a></div>

    '
paths:
  /buckslips/{buckslip_id}/orders:
    parameters:
    - in: path
      name: buckslip_id
      description: The ID of the buckslip to which the buckslip orders belong.
      required: true
      schema:
        $ref: '#/components/schemas/buckslip_id'
    get:
      operationId: buckslip_orders_retrieve
      summary: Retrieve
      description: Retrieves the buckslip orders associated with the given buckslip id.
      tags:
      - Buckslip Orders
      parameters:
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/offset'
      responses:
        '200':
          description: Returns the buckslip orders associated with the given buckslip id
          content:
            $ref: '#/components/mediaTypes/all_buckslip_orders'
        default:
          $ref: '#/components/responses/buckslip_order_error'
      x-codeSamples:
      - lang: Shell
        source: "curl https://api.lob.com/v1/buckslips/bck_6afffd19045076c/orders/ \\\n  -u <YOUR API KEY>:\n"
        label: CURL
    post:
      operationId: buckslip_order_create
      summary: Create
      description: Creates a new buckslip order given information
      tags:
      - Buckslip Orders
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/buckslip_order_editable'
            example:
              quantity: 10000
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/buckslip_order_editable'
            example:
              quantity: 10000
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/buckslip_order_editable'
            example:
              quantity: 10000
      responses:
        '200':
          description: Buckslip order created successfully
          content:
            $ref: '#/components/mediaTypes/buckslip_order'
        default:
          $ref: '#/components/responses/buckslip_error'
      x-codeSamples:
      - lang: Shell
        source: "curl https://api.lob.com/v1/buckslips/bck_6afffd19045076c/orders \\\n  -u <YOUR API KEY>: \\\n  -d \"quantity=10000\"\n"
        label: CURL
components:
  schemas:
    buckslip_order_editable:
      type: object
      required:
      - quantity
      properties:
        quantity:
          type: integer
          description: The quantity of buckslips in the order (minimum 5,000).
          minimum: 5000
          maximum: 10000000
    buckslip_id:
      type: string
      description: Unique identifier prefixed with `bck_`.
      pattern: ^bck_[a-zA-Z0-9]+$
    object:
      type: string
      description: Value is resource type.
    date_created:
      type: string
      format: date-time
      description: A timestamp in ISO 8601 format of the date the resource was created.
    lob_base:
      type: object
      required:
      - date_created
      - date_modified
      - object
      properties:
        date_created:
          $ref: '#/components/schemas/date_created'
        date_modified:
          $ref: '#/components/schemas/date_modified'
        deleted:
          $ref: '#/components/schemas/deleted'
        object:
          $ref: '#/components/schemas/object'
    list:
      type: object
      description: Multiple items returned in order
      properties:
        object:
          $ref: '#/components/schemas/object'
        next_url:
          type: string
          description: Url of next page of items in list.
          nullable: true
        previous_url:
          type: string
          description: Url of previous page of items in list.
          nullable: true
        count:
          $ref: '#/components/schemas/count'
        total_count:
          type: integer
          description: Indicates the total number of records. Provided when the request specifies an "include" query parameter
    date_modified:
      type: string
      format: date-time
      description: A timestamp in ISO 8601 format of the date the resource was last modified.
    bo_id:
      type: string
      description: Unique identifier prefixed with `bo_`.
      pattern: ^bo_[a-zA-Z0-9]+$
    deleted:
      type: boolean
      description: Only returned if the resource has been successfully deleted.
    count:
      type: integer
      description: number of resources in a set
    error:
      type: object
      description: Lob uses RESTful HTTP response codes to indicate success or failure of an API request. In general, 2xx indicates success, 4xx indicate an input error, and 5xx indicates an error on Lob's end.
      required:
      - error
      properties:
        error:
          type: object
          required:
          - message
          - status_code
          - code
          properties:
            message:
              type: string
              description: A human-readable message with more details about the error
              example: Rate limit exceeded. Please wait 5 seconds and try your request again.
            status_code:
              $ref: '#/components/schemas/failure_status_code'
            code:
              type: string
              enum:
              - bad_request
              - conflict
              - feature_limit_reached
              - internal_server_error
              - invalid
              - not_deletable
              - not_found
              - request_timeout
              - service_unavailable
              - unrecognized_endpoint
              - unsupported_lob_version
              - address_length_exceeds_limit
              - bank_account_already_verified
              - bank_error
              - billing_address_required
              - custom_envelope_inventory_depleted
              - deleted_bank_account
              - failed_deliverability_strictness
              - file_pages_below_min
              - file_pages_exceed_max
              - file_size_exceeds_limit
              - foreign_return_address
              - inconsistent_page_dimensions
              - invalid_bank_account
              - invalid_bank_account_verification
              - invalid_check_international
              - invalid_country_covid
              - invalid_file
              - invalid_file_dimensions
              - invalid_file_download_time
              - invalid_file_url
              - invalid_image_dpi
              - invalid_international_feature
              - invalid_perforation_return_envelope
              - invalid_template_html
              - mail_use_type_can_not_be_null
              - merge_variable_required
              - merge_variable_whitespace
              - payment_method_unverified
              - pdf_encrypted
              - special_characters_restricted
              - unembedded_fonts
              - email_required
              - invalid_api_key
              - publishable_key_not_allowed
              - rate_limit_exceeded
              - unauthorized
              - unauthorized_token
              description: 'A pre-defined string identifying an error. Error codes fall into three categories:


                **GENERIC**

                * `bad_request` - 422: an invalid request was made. See error message for details.

                * `conflict` - 409/422: this operation would leave data in a conflicted state.

                * `feature_limit_reached` - 403: the account has reached its resource limit and requires upgrading to add more.

                * `internal_server_error` - 500: an error has occured on Lob''s servers. Please try request again.

                * `invalid` - 422: an invalid request was made. See error message for details.

                * `not_deletable` - 422: an attempt was made to delete a resource, but the resource cannot be deleted.

                * `not_found` - 404: the requested resource was not found.

                * `request_timeout` - 408: the request took too long. Please try again.

                * `service_unavailable` - 503: the Lob servers are temporarily unavailable. Please try agian.

                * `unrecognized_endpoint` - 404: the requested endpoint doesn''t exist.

                * `unsupported_lob_version` - 422: an unsupported Lob API version was requested.


                **ADVANCED**

                * `address_length_exceeds_limit` - 422: the sum of to.address_line1 and to.address_line2 cannot surpass 50 characters.

                * `bank_account_already_verified` - 422: the bank account has already been verified.

                * `bank_error` - 422: there''s an issue with the bank account.

                * `billing_address_required` - 403: in order to create a live mail piece, your account needs to set up a billing address.

                * `custom_envelope_inventory_depleted` - 422: custom envelope inventory is depleted, and more will need to be ordered.

                * `deleted_bank_account` - 404: checks cannot be created with a deleted bank account.

                * `failed_deliverability_strictness` - 422: the `to` address doesn''t meet strictness requirements. See <a href="https://dashboard.lob.com/#/settings/account" target="_blank">Account Settings</a> to configure strictness.

                * `file_pages_below_min` - 422: not enough pages.

                * `file_pages_exceed_max` - 422: too many pages.

                * `file_size_exceeds_limit` - 422: the file size is too large. See description for details.

                * `foreign_return_address` - 422: the `from` address must be a US address.

                * `inconsistent_page_dimensions` - 422: all pages of the input file must have the same dimensions.

                * `invalid_bank_account` - 422: the provided bank routing number is invalid.

                * `invalid_bank_account_verification` - 422: verification amounts do not match.

                * `invalid_check_international` - 422: checks cannot be sent internationally.

                * `invalid_country_covid` - 422: the postal service in the specified country is currently unable to process the request due to COVID-19 restrictions.

                * `invalid_file` - 422: the file is invalid.

                * `invalid_file_dimensions` - 422: file dimensions are incorrect for the selected mail type.

                * `invalid_file_download_time` - 422: file download from remote server took too long.

                * `invalid_file_url` - 422: the file URL when creating a resource is invalid.

                * `invalid_image_dpi` - 422: DPI must be at least 300.

                * `invalid_international_feature` - 422: the specified product cannot be sent to the destination.

                * `invalid_perforation_return_envelope` - 422: both `return_envelope` and `perforation` must be used together.

                * `invalid_template_html` - 422: the provided HTML is invalid.

                * `mail_use_type_can_not_be_null` - 422: use_type must be one of "marketing" or "operational". Alternatively, an admin can set the account default use type in Account Settings.

                * `merge_variable_required` - 422: a required merge variable is missing.

                * `merge_variable_whitespace` - 422: merge variable names cannot contain whitespace.

                * `payment_method_unverified` - 401: you must have a verified bank account or credit card to submit live requests.

                * `pdf_encrypted` - 422: an encrypted PDF was provided.

                * `special_characters_restricted` - 422: cannot use special characters for merge variable names.

                * `unembedded_fonts` - 422: the provided PDF contains non-standard unembedded fonts. See description for details.


                **AUTHENTICATION**

                * `email_required` - 401: account must have a verified email address before creating live resources.

                * `invalid_api_key` - 401/403: the API key is invalid.

                * `publishable_key_not_allowed` - 403: the requested operation needs a secret key, not a publishable key. See [API Keys](#section/API-Keys) for more information.

                * `rate_limit_exceeded` - 429: requests were sent too quickly and must be slowed down.

                * `unauthorized` - 401: the request isn''t authorized.

                * `unauthorized_token` - 401: token isn''t authorized.

                '
    failure_status_code:
      type: integer
      enum:
      - 401
      - 403
      - 404
      - 413
      - 422
      - 429
      - 500
      description: "A conventional HTTP status code:\n  * `401` - Authorization error with your API key or account\n  * `403` - Forbidden error with your API key or account\n  * `404` - The requested item does not exist\n  * `413` - Payload too large\n  * `422` - The query or body parameters did not pass validation\n  * `429` - Too many requests have been sent with an API key in a given amount of time\n  * `500` - An internal server error occurred, please contact support@lob.com\n"
    buckslip_order:
      allOf:
      - $ref: '#/components/schemas/lob_base'
      - type: object
        properties:
          id:
            $ref: '#/components/schemas/bo_id'
          buckslip_id:
            $ref: '#/components/schemas/buckslip_id'
          status:
            description: The status of the buckslip order.
            enum:
            - pending
            - printing
            - available
            - cancelled
            - depleted
            type: string
          quantity_ordered:
            description: The quantity of buckslips ordered.
            type: number
            default: 0
          unit_price:
            description: The unit price for the buckslip order.
            type: number
            default: 0
          inventory:
            description: The inventory of the buckslip order.
            type: number
            default: 0
          cancelled_reason:
            description: The reason for cancellation.
            type: string
          availability_date:
            type: string
            format: date-time
            description: A timestamp in ISO 8601 format of the date the resource was created.
          expected_availability_date:
            type: string
            format: date-time
            description: The fixed deadline for the buckslips to be printed.
  mediaTypes:
    buckslip_order:
      application/json:
        schema:
          $ref: '#/components/schemas/buckslip_order'
        examples:
          basic:
            value:
              id: bo_e0f8a0562a06bea7f
              buckslip_id: bck_6afffd19045076c
              status: available
              quantity_ordered: 10000
              unit_price: 0.75
              cancelled_reason: No longer needed
              availability_date: '2021-10-12T21:41:48.326Z'
              expected_availability_date: '2021-11-04T21:03:18.871Z'
              date_created: '2021-10-07T21:03:18.871Z'
              date_modified: '2021-10-16T01:00:30.144Z'
              object: buckslip_order
    all_buckslip_orders:
      application/json:
        schema:
          allOf:
          - $ref: '#/components/schemas/list'
          - type: object
            properties:
              data:
                type: array
                description: List of buckslip orders
                items:
                  $ref: '#/components/schemas/buckslip_order'
        example:
          data:
          - id: bo_e0f8a0562a06bea7f
            buckslip_id: bck_6afffd19045076c
            status: available
            quantity_ordered: 5000
            unit_price: 0.75
            cancelled_reason: No longer needed
            availability_date: '2021-10-12T21:41:48.326Z'
            expected_availability_date: '2021-11-04T21:03:18.871Z'
            date_created: '2021-10-07T21:03:18.871Z'
            date_modified: '2021-10-16T01:00:30.144Z'
            object: buckslip_order
          object: list
          next_url: null
          previous_url: null
          count: 1
  parameters:
    offset:
      in: query
      name: offset
      required: false
      description: An integer that designates the offset at which to begin returning results. Defaults to 0.
      schema:
        type: integer
        default: 0
    limit:
      in: query
      name: limit
      required: false
      description: How many results to return.
      schema:
        type: integer
        minimum: 1
        default: 10
        maximum: 100
        example: 10
  responses:
    buckslip_order_error:
      description: Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
          example:
            error:
              code: not_found
              message: buckslip not found
              status_code: 404
    buckslip_error:
      description: Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
          example:
            error:
              code: invalid
              message: message about incorrect parameter
              status_code: 422
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
x-webhooks:
  events:
    post:
      summary: Events
      description: Information about an event
      operationId: event
      tags:
      - Events
      responses:
        '200':
          $ref: '#/components/responses/events'
  tracking_events:
    post:
      summary: Tracking Events
      description: Information about tracking events
      operationId: tracking_event
      tags:
      - Tracking Events
      responses:
        '200':
          $ref: '#/components/responses/tracking_events'
x-tagGroups:
- name: Overview
  tags:
  - Introduction
  - Authentication
  - Getting Started
  - SDKs and Tools
- name: Address Book
  tags:
  - Addresses
  - National Change of Address
- name: Print and Mail API
  tags:
  - Postcards
  - Self Mailers
  - Letters
  - Checks
  - Snap Packs
  - Booklets
  - Bank Accounts
  - Templates
  - Resource Proofs
  - Template Versions
  - Template Design
  - Manage Mail
- name: Campaigns API (BETA)
  tags:
  - Campaigns
  - Creatives
  - Uploads
- name: Informed Delivery Campaign API
  tags:
  - Informed Delivery Campaign
- name: Address Verification API
  tags:
  - US Verifications
  - US Verification Types
  - US Autocompletions
  - Reverse Geocode Lookups
  - Zip Lookups
  - Identity Validation
  - Intl Verifications
- name: Webhooks
  tags:
  - Webhooks
  - Events
  - Tracking Events
- name: Special Features
  tags:
  - Billing Groups
  - Buckslips
  - Buckslip Orders
  - Cards
  - Card Orders
  - QR Codes
  - URL Shortener
- name: Appendix
  tags:
  - Beta Program
  - Errors
  - Rate Limiting
  - Requests and Responses
  - Test and Live Environments
  - Versioning and Changelog
