openapi: 3.2.0
info:
  title: Lob Identity Validation API
  version: 1.22.0
  description: 'The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p>

    '
  license:
    name: MIT
    url: https://mit-license.org/
  contact:
    name: Lob Developer Experience
    url: https://support.lob.com/
    email: lob-openapi@lob.com
  termsOfService: https://www.lob.com/legal
servers:
- url: https://api.lob.com/v1
  description: production
security:
- basicAuth: []
tags:
- name: Identity Validation
  description: 'Validates whether a given name is associated with an address.

    <div class="back-to-top" ><a href="#" onclick="toTopLink()">back to top</a></div>

    '
paths:
  /identity_validation:
    post:
      operationId: identity_validation
      summary: Identity Validation
      description: Validates whether a given name is associated with an address.
      tags:
      - Identity Validation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/identity_validation_writable'
            example:
              recipient: Larry Lobster
              primary_line: 210 King St.
              secondary_line: ''
              city: San Francisco
              state: CA
              zip_code: '94107'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/identity_validation_writable'
            example:
              recipient: Larry Lobster
              primary_line: 210 King St.
              secondary_line: ''
              city: San Francisco
              state: CA
              zip_code: '94107'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/identity_validation_writable'
            example:
              recipient: Larry Lobster
              primary_line: 210 King St.
              secondary_line: ''
              city: San Francisco
              state: CA
              zip_code: '94107'
      responses:
        '200':
          $ref: '#/components/responses/identity_validation'
        default:
          $ref: '#/components/responses/identity_validation_error'
      x-codeSamples:
      - lang: Shell
        source: "curl https://api.lob.com/v1/identity_validation \\\n  -u <YOUR_LIVE_API_KEY>: \\\n  -d \"recipient=Larry Lobster\" \\\n  -d \"primary_line=210 King St\" \\\n  -d \"secondary_line=\" \\\n  -d \"urbanization=\" \\\n  -d \"city=San Francsico\" \\\n  -d \"state=CA\" \\\n  -d \"zip_code=94107\" \\\n"
        label: CURL
components:
  schemas:
    failure_status_code:
      type: integer
      enum:
      - 401
      - 403
      - 404
      - 413
      - 422
      - 429
      - 500
      description: "A conventional HTTP status code:\n  * `401` - Authorization error with your API key or account\n  * `403` - Forbidden error with your API key or account\n  * `404` - The requested item does not exist\n  * `413` - Payload too large\n  * `422` - The query or body parameters did not pass validation\n  * `429` - Too many requests have been sent with an API key in a given amount of time\n  * `500` - An internal server error occurred, please contact support@lob.com\n"
    identity_validation:
      oneOf:
      - $ref: '#/components/schemas/recipient_validation'
      - $ref: '#/components/schemas/company_validation'
    identity_validation_id:
      type: string
      description: Unique identifier prefixed with `id_validation_`.
      pattern: ^id_validation_[a-zA-Z0-9_]+$
    identity_validation_recipient:
      type:
      - string
      - 'null'
      description: The name of the person whose identity is being validated.
      maxLength: 500
    error:
      type: object
      description: Lob uses RESTful HTTP response codes to indicate success or failure of an API request. In general, 2xx indicates success, 4xx indicate an input error, and 5xx indicates an error on Lob's end.
      required:
      - error
      properties:
        error:
          type: object
          required:
          - message
          - status_code
          - code
          properties:
            message:
              type: string
              description: A human-readable message with more details about the error
              example: Rate limit exceeded. Please wait 5 seconds and try your request again.
            status_code:
              $ref: '#/components/schemas/failure_status_code'
            code:
              type: string
              enum:
              - bad_request
              - conflict
              - feature_limit_reached
              - internal_server_error
              - invalid
              - not_deletable
              - not_found
              - request_timeout
              - service_unavailable
              - unrecognized_endpoint
              - unsupported_lob_version
              - address_length_exceeds_limit
              - bank_account_already_verified
              - bank_error
              - billing_address_required
              - custom_envelope_inventory_depleted
              - deleted_bank_account
              - failed_deliverability_strictness
              - file_pages_below_min
              - file_pages_exceed_max
              - file_size_exceeds_limit
              - foreign_return_address
              - inconsistent_page_dimensions
              - invalid_bank_account
              - invalid_bank_account_verification
              - invalid_check_international
              - invalid_country_covid
              - invalid_file
              - invalid_file_dimensions
              - invalid_file_download_time
              - invalid_file_url
              - invalid_image_dpi
              - invalid_international_feature
              - invalid_perforation_return_envelope
              - invalid_template_html
              - mail_use_type_can_not_be_null
              - merge_variable_required
              - merge_variable_whitespace
              - payment_method_unverified
              - pdf_encrypted
              - special_characters_restricted
              - unembedded_fonts
              - email_required
              - invalid_api_key
              - publishable_key_not_allowed
              - rate_limit_exceeded
              - unauthorized
              - unauthorized_token
              description: 'A pre-defined string identifying an error. Error codes fall into three categories:


                **GENERIC**

                * `bad_request` - 422: an invalid request was made. See error message for details.

                * `conflict` - 409/422: this operation would leave data in a conflicted state.

                * `feature_limit_reached` - 403: the account has reached its resource limit and requires upgrading to add more.

                * `internal_server_error` - 500: an error has occured on Lob''s servers. Please try request again.

                * `invalid` - 422: an invalid request was made. See error message for details.

                * `not_deletable` - 422: an attempt was made to delete a resource, but the resource cannot be deleted.

                * `not_found` - 404: the requested resource was not found.

                * `request_timeout` - 408: the request took too long. Please try again.

                * `service_unavailable` - 503: the Lob servers are temporarily unavailable. Please try agian.

                * `unrecognized_endpoint` - 404: the requested endpoint doesn''t exist.

                * `unsupported_lob_version` - 422: an unsupported Lob API version was requested.


                **ADVANCED**

                * `address_length_exceeds_limit` - 422: the sum of to.address_line1 and to.address_line2 cannot surpass 50 characters.

                * `bank_account_already_verified` - 422: the bank account has already been verified.

                * `bank_error` - 422: there''s an issue with the bank account.

                * `billing_address_required` - 403: in order to create a live mail piece, your account needs to set up a billing address.

                * `custom_envelope_inventory_depleted` - 422: custom envelope inventory is depleted, and more will need to be ordered.

                * `deleted_bank_account` - 404: checks cannot be created with a deleted bank account.

                * `failed_deliverability_strictness` - 422: the `to` address doesn''t meet strictness requirements. See <a href="https://dashboard.lob.com/#/settings/account" target="_blank">Account Settings</a> to configure strictness.

                * `file_pages_below_min` - 422: not enough pages.

                * `file_pages_exceed_max` - 422: too many pages.

                * `file_size_exceeds_limit` - 422: the file size is too large. See description for details.

                * `foreign_return_address` - 422: the `from` address must be a US address.

                * `inconsistent_page_dimensions` - 422: all pages of the input file must have the same dimensions.

                * `invalid_bank_account` - 422: the provided bank routing number is invalid.

                * `invalid_bank_account_verification` - 422: verification amounts do not match.

                * `invalid_check_international` - 422: checks cannot be sent internationally.

                * `invalid_country_covid` - 422: the postal service in the specified country is currently unable to process the request due to COVID-19 restrictions.

                * `invalid_file` - 422: the file is invalid.

                * `invalid_file_dimensions` - 422: file dimensions are incorrect for the selected mail type.

                * `invalid_file_download_time` - 422: file download from remote server took too long.

                * `invalid_file_url` - 422: the file URL when creating a resource is invalid.

                * `invalid_image_dpi` - 422: DPI must be at least 300.

                * `invalid_international_feature` - 422: the specified product cannot be sent to the destination.

                * `invalid_perforation_return_envelope` - 422: both `return_envelope` and `perforation` must be used together.

                * `invalid_template_html` - 422: the provided HTML is invalid.

                * `mail_use_type_can_not_be_null` - 422: use_type must be one of "marketing" or "operational". Alternatively, an admin can set the account default use type in Account Settings.

                * `merge_variable_required` - 422: a required merge variable is missing.

                * `merge_variable_whitespace` - 422: merge variable names cannot contain whitespace.

                * `payment_method_unverified` - 401: you must have a verified bank account or credit card to submit live requests.

                * `pdf_encrypted` - 422: an encrypted PDF was provided.

                * `special_characters_restricted` - 422: cannot use special characters for merge variable names.

                * `unembedded_fonts` - 422: the provided PDF contains non-standard unembedded fonts. See description for details.


                **AUTHENTICATION**

                * `email_required` - 401: account must have a verified email address before creating live resources.

                * `invalid_api_key` - 401/403: the API key is invalid.

                * `publishable_key_not_allowed` - 403: the requested operation needs a secret key, not a publishable key. See [API Keys](#section/API-Keys) for more information.

                * `rate_limit_exceeded` - 429: requests were sent too quickly and must be slowed down.

                * `unauthorized` - 401: the request isn''t authorized.

                * `unauthorized_token` - 401: token isn''t authorized.

                '
    company_validation:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/identity_validation_id'
        company:
          $ref: '#/components/schemas/identity_validation_company'
        primary_line:
          $ref: '#/components/schemas/primary_line_us'
        secondary_line:
          $ref: '#/components/schemas/secondary_line'
        urbanization:
          $ref: '#/components/schemas/urbanization'
        last_line:
          type: string
          description: 'Combination of the following applicable `components`:

            * City (`city`)

            * State (`state`)

            * ZIP code (`zip_code`)

            * ZIP+4 (`zip_code_plus_4`)

            '
        score:
          type:
          - number
          - 'null'
          format: float
          description: 'A numerical score between 0 and 100 that represents the likelihood the provided name is associated with a physical address.

            '
          default: null
          minimum: 0
          maximum: 100
        confidence:
          type: string
          enum:
          - high
          - medium
          - low
          - ''
          description: 'Indicates the likelihood the recipient name and address match based on our custom internal calculation. Possible values are:

            - `high` — Has a Lob confidence score greater than 70.

            - `medium` — Has a Lob confidence score between 40 and 70.

            - `low` — Has a Lob confidence score less than 40.

            - `""` — No tracking data exists for this address.

            '
        object:
          type: string
          description: Value is resource type.
          enum:
          - id_validation
          default: id_validation
    secondary_line:
      type: string
      description: 'The secondary delivery line of the address. This field is typically empty but may contain information if `primary_line` is too long.

        '
      maxLength: 200
    recipient_validation:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/identity_validation_id'
        recipient:
          $ref: '#/components/schemas/identity_validation_recipient'
        primary_line:
          $ref: '#/components/schemas/primary_line_us'
        secondary_line:
          $ref: '#/components/schemas/secondary_line'
        urbanization:
          $ref: '#/components/schemas/urbanization'
        last_line:
          type: string
          description: 'Combination of the following applicable `components`:

            * City (`city`)

            * State (`state`)

            * ZIP code (`zip_code`)

            * ZIP+4 (`zip_code_plus_4`)

            '
        score:
          type:
          - number
          - 'null'
          format: float
          description: 'A numerical score between 0 and 100 that represents the likelihood the provided name is associated with a physical address.

            '
          default: null
          minimum: 0
          maximum: 100
        confidence:
          type: string
          enum:
          - high
          - medium
          - low
          - ''
          description: 'Indicates the likelihood the recipient name and address match based on our custom internal calculation. Possible values are:

            - `high` — Has a Lob confidence score greater than 70.

            - `medium` — Has a Lob confidence score between 40 and 70.

            - `low` — Has a Lob confidence score less than 40.

            - `""` — No tracking data exists for this address.

            '
        object:
          type: string
          description: Value is resource type.
          enum:
          - id_validation
          default: id_validation
    recipient:
      type:
      - string
      - 'null'
      description: The intended recipient, typically a person's or firm's name.
      maxLength: 500
    company_input:
      allOf:
      - anyOf:
        - title: Address object with `city` and `state`
          required:
          - city
          - state
        - title: Address object with `zip_code`
          required:
          - zip_code
      - type: object
        required:
        - company
        - primary_line
        properties:
          company:
            $ref: '#/components/schemas/identity_validation_company'
          primary_line:
            $ref: '#/components/schemas/primary_line_us'
          secondary_line:
            $ref: '#/components/schemas/secondary_line'
          urbanization:
            $ref: '#/components/schemas/urbanization'
          city:
            allOf:
            - $ref: '#/components/schemas/city_no_description'
            - type: string
              description: The name of the city. `city` and `state` are required if no `zip_code` is passed.
          state:
            type: string
            description: The <a href="https://en.wikipedia.org/wiki/ISO_3166-2:US" target="_blank">ISO 3166-2</a> two letter code or subdivision name for the state. `city` and `state` are required if no `zip_code` is passed.
            maxLength: 50
          zip_code:
            allOf:
            - type: string
              description: Required if `city` and `state` are not passed in. If included, must be formatted as a US ZIP or ZIP+4 (e.g. `94107`, `941072282`, `94107-2282`).
            - $ref: '#/components/schemas/zip_code'
    urbanization:
      type: string
      description: 'Only present for addresses in Puerto Rico. An urbanization refers to an area, sector, or development within a city. See <a href="https://pe.usps.com/text/pub28/28api_008.htm#:~:text=I51.,-4%20Urbanizations&text=In%20Puerto%20Rico%2C%20identical%20street,placed%20before%20the%20urbanization%20name." target="_blank">USPS documentation</a> for clarification.

        '
      maxLength: 200
    city_no_description:
      type: string
      maxLength: 200
    recipient_input:
      allOf:
      - anyOf:
        - title: Address object with `city` and `state`
          required:
          - city
          - state
        - title: Address object with `zip_code`
          required:
          - zip_code
      - type: object
        required:
        - recipient
        - primary_line
        properties:
          recipient:
            $ref: '#/components/schemas/recipient'
          primary_line:
            $ref: '#/components/schemas/primary_line_us'
          secondary_line:
            $ref: '#/components/schemas/secondary_line'
          urbanization:
            $ref: '#/components/schemas/urbanization'
          city:
            allOf:
            - $ref: '#/components/schemas/city_no_description'
            - type: string
              description: The name of the city. `city` and `state` are required if no `zip_code` is passed.
          state:
            type: string
            description: The <a href="https://en.wikipedia.org/wiki/ISO_3166-2:US" target="_blank">ISO 3166-2</a> two letter code or subdivision name for the state. `city` and `state` are required if no `zip_code` is passed.
            maxLength: 50
          zip_code:
            allOf:
            - description: Required if `city` and `state` are not passed in. If included, must be formatted as a US ZIP or ZIP+4 (e.g. `94107`, `941072282`, `94107-2282`).
            - $ref: '#/components/schemas/zip_code'
    primary_line_us:
      type: string
      description: 'The primary delivery line (usually the street address) of the address.

        Combination of the following applicable `components`:

        * `primary_number`

        * `street_predirection`

        * `street_name`

        * `street_suffix`

        * `street_postdirection`

        * `secondary_designator`

        * `secondary_number`

        * `pmb_designator`

        * `pmb_number`

        '
      maxLength: 200
    identity_validation_company:
      type:
      - string
      - 'null'
      description: The name of the company or firm.
      maxLength: 500
    identity_validation_writable:
      oneOf:
      - $ref: '#/components/schemas/recipient_input'
      - $ref: '#/components/schemas/company_input'
    zip_code:
      type: string
      pattern: ^\d{5}((-)?\d{4})?$
  responses:
    identity_validation:
      description: Returns the likelihood a given name is associated with an address.
      headers:
        ratelimit-limit:
          $ref: '#/components/headers/ratelimit-limit'
        ratelimit-remaining:
          $ref: '#/components/headers/ratelimit-remaining'
        ratelimit-reset:
          $ref: '#/components/headers/ratelimit-reset'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/identity_validation'
          example:
            id: id_validation_8a013f3e
            recipient: LARRY LOBSTER
            primary_line: 210 KING ST.
            secondary_line: ''
            urbanization: ''
            last_line: SAN FRANCISCO CA 94107-1728
            score: 100
            confidence: high
            object: id_validation
    identity_validation_error:
      description: Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
          example:
            error:
              code: invalid
              message: recipient is required
              status_code: 422
  headers:
    ratelimit-remaining:
      description: The number of requests remaining in the current window.
      schema:
        type: integer
        example: 100
    ratelimit-reset:
      description: 'The time at which the rate limit window resets in  <a href="https://en.wikipedia.org/wiki/Unix_time" target="_blank">UTC epoch seconds</a>

        '
      schema:
        type: integer
        example: 1528749846
    ratelimit-limit:
      description: The rate limit for a given endpoint.
      schema:
        type: integer
        example: 150
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
x-tagGroups:
- name: Overview
  tags:
  - Introduction
  - Authentication
  - Getting Started
  - SDKs and Tools
- name: Address Book
  tags:
  - Addresses
  - National Change of Address
- name: Print and Mail API
  tags:
  - Postcards
  - Self Mailers
  - Letters
  - Checks
  - Snap Packs
  - Booklets
  - Bank Accounts
  - Templates
  - Resource Proofs
  - Template Versions
  - Template Design
  - Manage Mail
- name: Campaigns API (BETA)
  tags:
  - Campaigns
  - Creatives
  - Uploads
- name: Informed Delivery Campaign API
  tags:
  - Informed Delivery Campaign
- name: Address Verification API
  tags:
  - US Verifications
  - US Verification Types
  - US Autocompletions
  - Reverse Geocode Lookups
  - Zip Lookups
  - Identity Validation
  - Intl Verifications
- name: Webhooks
  tags:
  - Webhooks
  - Events
  - Tracking Events
- name: Special Features
  tags:
  - Billing Groups
  - Buckslips
  - Buckslip Orders
  - Cards
  - Card Orders
  - QR Codes
  - URL Shortener
- name: Appendix
  tags:
  - Beta Program
  - Errors
  - Rate Limiting
  - Requests and Responses
  - Test and Live Environments
  - Versioning and Changelog
